server:
  port: 8282

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:banco;Mode=Oracle
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update